---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: app-continuum
- name: version

outputs:
- name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      cd app-continuum
      ./gradlew clean build
      cp application/build/libs/application.jar ../build-output/app-continuum-`cat ../version/number`.jar
