---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: app-continuum
- name: version

outputs:
- name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      export DEBIAN_FRONTEND="noninteractive"
      apt-get update
      apt-get -y install mariadb-server

      cd app-continuum

      service mysql start
      mysql -uroot < databases/create_databases.sql

      export SERVER_START_TIMEOUT=60
      ./gradlew testMigrate clean build
      cp application/build/libs/application.jar ../build-output/app-continuum-`cat ../version/number`.jar

      service mysql stop
